version: '3'

services:
  app:
    image: lbrunoq/golang-mysql
    container_name: app
    networks:
      - pfa_net
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=challenge
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
    networks:
      - pfa_net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - pfa_net
    links:
      - app

networks:
  pfa_net:
    driver: bridge
